version: '3.7'
services:
  inventory:
    build: .
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=inventory_admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=inventory
      - SERVER_PORT=8080
    ports: 
      - "8080:8080"
  db:
    image: mysql:8.0  
    environment:
      - MYSQL_USER=inventory_admin
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=inventory
    ports:
      - "3306:3306"