openapi: 3.0.0
info:
  title: Inventory Go
  version: 1.0.0
servers:
  - url: http://localhost:8080  # Update with your actual server URL

paths:
  /products:
    get:
      summary: Get a list of products
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: |
                [
                  {
                    "id": 1,
                    "name": "Product 1",
                    "price": 19.99
                  },
                  {
                    "id": 2,
                    "name": "Product 2",
                    "price": 29.99
                  }
                ]
        '500':
          description: Internal Server Error
  /product/{id}:
    get:
      summary: Get a product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the product
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: |
                {
                  "id": 1,
                  "name": "Product 1",
                  "price": 19.99
                }
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    put:
      summary: Update a product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
            example: |
              {
                "name": "Updated Product",
                "price": 24.99
              }
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    delete:
      summary: Delete a product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the product
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /product:
    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
            example: |
              {
                "name": "New Product",
                "price": 34.99
              }
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error